/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14/samples
 */
plugins {
    kotlin("jvm") version "1.6.10" // Apply the Kotlin JVM plugin
}

repositories {
    mavenCentral() // Use Maven Central for dependencies
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib") // Kotlin standard library
    implementation("org.apache.commons:commons-lang3:3.12.0") // Example dependency
}